Fixed test.
Error was:

List(true, true, true, true) did not equal true
ScalaTestFailureLocation: org.constellation.cluster.MultiNodeTest at (MultiNodeTest.scala:516)
Expected :true
Actual   :List(true, true, true, true)
 <Click to see difference>

org.scalatest.exceptions.TestFailedException: List(true, true, true, true) did not equal true
	at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:528)

Ignore the UDP bind errors, those are unrelated and due to us using the
default port (that can be fixed independently.)